# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craig D. French 
email: website@craigdfrench.io
description: > # this means to ignore newlines until "baseurl:"
  Professional Website for Craig D. French, P.Eng
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://craigdfrench.io" # the base hostname & protocol for your site
twitter_username: craigdfrench 
github_username:  craigdfrench

# Build settings
markdown: kramdown
host: 172.31.254.40 
port: 8080
